# SubSet of Array

In [3]:
import numpy as np
a= np.random.randint(10, size=(5,5))
a

array([[0, 1, 6, 0, 4],
       [8, 8, 8, 5, 1],
       [2, 1, 9, 7, 5],
       [4, 2, 6, 8, 9],
       [6, 0, 5, 9, 2]])

In [5]:
subSet_a=a[0:3,0:2]
subSet_a

array([[0, 1],
       [8, 8],
       [2, 1]])

In [6]:
subSet_a[0,0]=999
subSet_a[1,1]=888
subSet_a


array([[999,   1],
       [  8, 888],
       [  2,   1]])

In [7]:
a

array([[999,   1,   6,   0,   4],
       [  8, 888,   8,   5,   1],
       [  2,   1,   9,   7,   5],
       [  4,   2,   6,   8,   9],
       [  6,   0,   5,   9,   2]])

In [8]:
b=np.random.randint(10, size=(5,5))
b

array([[4, 5, 7, 1, 9],
       [0, 8, 7, 6, 2],
       [4, 5, 5, 7, 6],
       [0, 7, 9, 3, 1],
       [1, 2, 7, 5, 3]])

In [9]:
subSet_b=b[0:3,0:2].copy()
subSet_b

array([[4, 5],
       [0, 8],
       [4, 5]])

In [10]:
subSet_b[0,0]=999
subSet_b[1,1]=777
subSet_b

array([[999,   5],
       [  0, 777],
       [  4,   5]])

In [11]:
b

array([[4, 5, 7, 1, 9],
       [0, 8, 7, 6, 2],
       [4, 5, 5, 7, 6],
       [0, 7, 9, 3, 1],
       [1, 2, 7, 5, 3]])

# Fancy Index

In [13]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
fancyIndex=[1,3,5]
v[fancyIndex]

array([ 3,  9, 15])

In [15]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
m1=np.array([0,1])
m2=np.array([1,2])


In [17]:
m[m1,m2]

array([1, 5])

In [18]:
m[0,m1]

array([0, 1])

In [21]:
# slice and fancy

In [22]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
 m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Conditional Elemets Operators

In [29]:
v=np.array([1,2,3,4,5])

In [30]:
v<5

array([ True,  True,  True,  True, False])

In [31]:
v[v<3]

array([1, 2])

In [33]:
v[v==2]

array([2])

In [34]:
v[v!=2]

array([1, 3, 4, 5])

# Equation Solving 

## 5*x+y=12
## x+3*y=10

In [50]:
s1=np.array([[5,1],[1,3]])
s2=np.array([12,10])

In [44]:
s1

array([[5, 1],
       [1, 3]])

In [51]:
s2

array([12, 10])

In [53]:
s = np.linalg.solve(s1,s2)

In [54]:
s

array([1.85714286, 2.71428571])